{
  "formatVersion": "1.1",
  "component": {
    "group": "cc.banzhi.runtrace",
    "module": "RunTracePlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dne7nqv46ja3zgu5nmw5kpuxb4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RunTracePlugin-1.0.0.jar",
          "url": "RunTracePlugin-1.0.0.jar",
          "size": 26940,
          "sha512": "0cf366adf5bfcefedc25ce2c75ab9420cbd0c8404e92d2b9fb5b5874b8b0bcab32c9f2b03ca62736702b2a3cba3c5fda5a190e3dee0e404a41c9985e273dc720",
          "sha256": "2b063cbf4dfd8ffc27d5616f55735946942c4fcb1f00a56db040be4595af31a6",
          "sha1": "40f14ac4bb3440f2717e5866cc9b6afa8c01571b",
          "md5": "a7a9a7e36e8566c390cf14fbe2fe3b31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "RunTracePlugin-1.0.0.jar",
          "url": "RunTracePlugin-1.0.0.jar",
          "size": 26940,
          "sha512": "0cf366adf5bfcefedc25ce2c75ab9420cbd0c8404e92d2b9fb5b5874b8b0bcab32c9f2b03ca62736702b2a3cba3c5fda5a190e3dee0e404a41c9985e273dc720",
          "sha256": "2b063cbf4dfd8ffc27d5616f55735946942c4fcb1f00a56db040be4595af31a6",
          "sha1": "40f14ac4bb3440f2717e5866cc9b6afa8c01571b",
          "md5": "a7a9a7e36e8566c390cf14fbe2fe3b31"
        }
      ]
    }
  ]
}
