{
  "formatVersion": "1.1",
  "component": {
    "group": "cc.banzhi.runtrace",
    "module": "RunTracePlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xygkrmedhre7ddu3nqxkf26ce4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RunTracePlugin-1.0.0.jar",
          "url": "RunTracePlugin-1.0.0.jar",
          "size": 24944,
          "sha512": "7d028414a9e447dc1a9a635fbdadaa8f8c81ef3bf7138fade48c6803e7da0438ceae1fcc97c21df8338bc4afa9bb8eed9c9f5a382d3d26961738bc10ca6209cc",
          "sha256": "f1d27b5caeb12c526ffbaa25e2394972e952c776c5f62470212f7b8eb02f5cd5",
          "sha1": "d561091da41543ff1c47611062428842dc721de4",
          "md5": "69f3b275ca88ef25f5584eef8e60b916"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "RunTracePlugin-1.0.0.jar",
          "url": "RunTracePlugin-1.0.0.jar",
          "size": 24944,
          "sha512": "7d028414a9e447dc1a9a635fbdadaa8f8c81ef3bf7138fade48c6803e7da0438ceae1fcc97c21df8338bc4afa9bb8eed9c9f5a382d3d26961738bc10ca6209cc",
          "sha256": "f1d27b5caeb12c526ffbaa25e2394972e952c776c5f62470212f7b8eb02f5cd5",
          "sha1": "d561091da41543ff1c47611062428842dc721de4",
          "md5": "69f3b275ca88ef25f5584eef8e60b916"
        }
      ]
    }
  ]
}
