{
  "formatVersion": "1.1",
  "component": {
    "group": "cc.banzhi.runtrace",
    "module": "RunTracePlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "z3dnmjsxsfbphoalhqyrpj5w64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RunTracePlugin-1.0.0.jar",
          "url": "RunTracePlugin-1.0.0.jar",
          "size": 12828,
          "sha512": "54d133590282ac730637b4bedfc36dccc002549b7d69d9fb9e99ffdca12893100f4faf352d28c695518f8e428b8af836cc0f8a56296d3efeb2dbc9e3b52b4a80",
          "sha256": "50039a793b8765e745e7ed9704928058792d661dad78446ab3adfac6442067b6",
          "sha1": "c6d3c82bf4cec5099b503565d5febc159b0c40d9",
          "md5": "eae0fed8cc7a5873f782161f6142aab8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "RunTracePlugin-1.0.0.jar",
          "url": "RunTracePlugin-1.0.0.jar",
          "size": 12828,
          "sha512": "54d133590282ac730637b4bedfc36dccc002549b7d69d9fb9e99ffdca12893100f4faf352d28c695518f8e428b8af836cc0f8a56296d3efeb2dbc9e3b52b4a80",
          "sha256": "50039a793b8765e745e7ed9704928058792d661dad78446ab3adfac6442067b6",
          "sha1": "c6d3c82bf4cec5099b503565d5febc159b0c40d9",
          "md5": "eae0fed8cc7a5873f782161f6142aab8"
        }
      ]
    }
  ]
}
